2021-11-08 16:47:19,013 - instabot version: 0.117.0 (bot) - INFO - Instabot version: 0.117.0 Started
2021-11-08 16:47:19,014 - instabot version: 0.117.0 (bot) - DEBUG - Bot imported from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instabot/bot/bot.py
2021-11-08 16:47:19,014 - instabot version: 0.117.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2021-11-08 16:48:49,272 - instabot version: 0.117.0 (api) - WARNING - HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/accounts/get_prefill_candidates/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7f149a3550>: Failed to establish a new connection: [Errno 61] Connection refused')))
